#!/usr/bin/python3
import tkinter as tk

def clicked():
    print("clicked")

root = tk.Tk()

button = tk.Button(
    root,
    text="Please replace the dust boot.",
    command=clicked,
    anchor="center"
)

root.mainloop()

